### ISSUE TITLE
퍼가요~

### ISSUE THREAD

**Issue by sdk-kr** [woosungchoi/docker-gnuboard#38]
https://github.com/woosungchoi/docker-gnuboard/blob/b30b4ac74b5579e5be54d9cc8ce5a0d33016929e/build/Dockerfile#L1

이부분만 퍼갈게요
잘 만들어져 있어서요

https://github.com/sundoforce/fpm-alpine
우성짱님거 fork했긴 했는데
fork안하고 우성짱님것 써도 될것 같아요

**Comment by sundoforce** [comment]
감사합니다.
